# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_demo', '0004_auto_20180711_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attr',
            field=models.CharField(blank=True, choices=[('c', '\u56fd\u5185\u5927\u5b66'), ('f', '\u56fd\u5916\u5927\u5b66'), ('g', '\u6e38\u620f'), ('sta', '\u660e\u661f'), ('sto', '\u80a1\u7968'), ('bo', '\u8bfb\u4e66'), ('sp', '\u4f53\u80b2'), ('car', '\u8f66'), ('mu', '\u97f3\u4e50'), ('mo', '\u7535\u5f71')], max_length=20, null=True, verbose_name='\u4e8b\u4ef6\u5c5e\u6027'),
        ),
    ]
