# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_demo', '0005_auto_20180711_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_address',
            new_name='eaddress',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_balance',
            new_name='ebalance',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_name',
            new_name='ename',
        ),
    ]
