# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_demo', '0006_auto_20180711_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eaddress',
            new_name='e_address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ebalance',
            new_name='e_balance',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='ename',
            new_name='e_name',
        ),
    ]
